package com.weaver.config;

import org.apache.ibatis.annotations.InsertProvider;

import java.util.List;

/**
 * @author lzy
 * @version v1.0
 * @description
 * @date:22/02/24 18:03
 */
@tk.mybatis.mapper.annotation.RegisterMapper
public interface BatchInsertListMapper<T> {

    @InsertProvider(type = MySpecialProvider.class, method = "dynamicSQL")
    int batchInsertListAutoGenerated(List<? extends T> recordList);

    @InsertProvider(type = MySpecialProvider.class, method = "dynamicSQL")
    int batchInsertList(List<? extends T> recordList);

}
